# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
namespace: tiller-world

image: hazzindu/bluegreen:1.0.2

deployment:
  # method: rolling-upgrade
 method: bluegreen
 active: blue
 activeImage: hazzindu/bluegreen:1.0.8

ingress:
  strategicDomain: 
    name: www.abc.com
    path: "/"
#    tls: true
    ssl: true
    httpsOnly: true
    httpsBackend: false
  tacticalDomain: 
    name: www.abc.tech
    path: "/"
#    tls: true
    ssl: true
    httpsOnly: true
    httpsBackend: false

  technicalDomain: 
    name: www.abc.io
    path: "/"
#    tls: false
    ssl: false
    httpsOnly: false
    httpsBackend: false

