---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: bluegreen
  namespace: bluegreen
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1.0
spec:
  releaseName: bluegreen
  chart:
    git: ssh://git@github.com/hasindum/bluegreenconfig
    ref: master
    path: charts/bluegreen
  values:
    image: hazzindu/bluegreen:1.0.7
    deployment:
      method: rolling-upgrade
      # method: bluegreen
      # active: blue
    persistence:
      enabled: false
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
    serviceType: ClusterIP
