---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: bluegreen
  namespace: bluegreen
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1.0
spec:
  releaseName: bluegreen
  chart:
    git: ssh://git@github.com/hasindum/bluegreenconfig
    ref: master
    path: charts/bluegreen
  values:
<<<<<<< HEAD
    image: hazzindu/bluegreen:1.0.4
    deployment:
      # method: rolling-upgrade
      method: bluegreen
      active: blue
=======
    image: hazzindu/bluegreen:1.0.5
>>>>>>> e967e520a849b355a38ed1af85a835e1b0a44874
    persistence:
      enabled: false
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
    serviceType: ClusterIP
