---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: bluegreen
  namespace: bluegreen
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: bluegreen
  chart:
    git: ssh://git@github.com/hasindum/bluegreenconfig
    ref: master
    path: charts/bluegreen
  values:
    image: hazzindu/bluegreen:dev-1.0.0
    persistence:
      enabled: false
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
    serviceType: ClusterIP
