{{- if eq .Values.deployment.method "bluegreen"}}
{{- if .Values.ingress.strategicDomain.enabled }}
{{- $fullName := .Release.Name -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-strategicdomain
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "blue-green.name" . }}
    chart: {{ template "blue-green.chart" . }}
    release: {{ .Release.Name }}
    ssl: "false"
    httpsOnly: "true"
    httpsBackend: "false"
spec:
  rules:
  {{- if .Values.ingress.strategicDomain.name }}
  - host: {{ .Values.ingress.strategicDomain.name }}
    http:
      paths:
        - path: {{ .Values.ingress.strategicDomain.path | default "/" }}
          backend:
            serviceName: {{ $fullName }}-{{ .Values.deployment.active }}
            servicePort: http
  {{- end }}
{{- end }}
{{- end }}
