{{- if eq .Values.deployment.method "bluegreen"}}
{{- if .Values.ingress.tacticalDomain.enabled }}
{{- $fullName := .Release.Name -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-tacticaldomain-green
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "blue-green.name" . }}
    chart: {{ template "blue-green.chart" . }}
    release: {{ .Release.Name }}
spec:
  rules:
  {{- if .Values.ingress.tacticalDomain.name }}
  - host: green-{{ .Values.ingress.tacticalDomain.name }}
    http:
      paths:
        - path: {{ .Values.ingress.tacticalDomain.path | default "/" }}
          backend:
            serviceName: {{ $fullName }}-green
            servicePort: http
  {{- end }}
{{- end }}
{{- end }}
